# Generated by Django 5.1.6 on 2025-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('investment_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tabletemplateitem',
            unique_together={('template', 'security')},
        ),
        migrations.AddConstraint(
            model_name='tabletemplateitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='weight_limit'),
        ),
    ]
