# Generated by Django 5.1.6 on 2025-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tables', '0002_alter_tabletemplateitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemplate',
            name='slug',
            field=models.SlugField(default='table', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabletemplateitem',
            name='weight',
            field=models.FloatField(help_text='in %'),
        ),
        migrations.AlterUniqueTogether(
            name='tablesnapshotitem',
            unique_together={('snapshot', 'template_item')},
        ),
    ]
