# Generated by Django 5.1.6 on 2025-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tables', '0003_tabletemplate_slug_alter_tabletemplateitem_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemplateitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
