# Generated by Django 5.1.6 on 2025-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tables', '0004_tabletemplateitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesnapshotitem',
            name='coefficient',
            field=models.FloatField(default=1),
        ),
    ]
