# Generated by Django 5.1.6 on 2025-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tables', '0005_tablesnapshotitem_coefficient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tablesnapshotitem',
            constraint=models.CheckConstraint(condition=models.Q(('coefficient__gte', 0)), name='coefficient_is_not_negative'),
        ),
    ]
