# Generated by Django 5.1.6 on 2025-03-10 22:33

import users.models.itable_user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_itableuser_email_alter_itableuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='itableuser',
            managers=[
                ('objects', users.models.itable_user.ItableUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='itableuser',
            name='username',
        ),
    ]
