# Generated by Django 5.1.6 on 2025-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_rename_user_portfolio_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
