# Generated by Django 5.1.6 on 2025-02-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='portfolio.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioitem',
            unique_together={('portfolio', 'security')},
        ),
    ]
