# Generated by Django 5.1.6 on 2025-02-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioitem_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='owner',
        ),
    ]
