# Generated by Django 5.1.6 on 2025-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tables', '0007_tablesnapshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesnapshot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
